apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: aws-hosted-cp-extended
  namespace: hmc-system
spec:
  providers:
    - bootstrap-k0smotron
    - control-plane-k0smotron
    - infrastructure-openstack
  helm:
    chartSpec:
      chart: aws-hosted-cp-extended
      sourceRef:
        kind: HelmRepository
        name: aws-hosted-cp-extended
