apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-hosted-cp-extended
  namespace: hmc-system
spec:
  insecure: true
  interval: 1m0s
  provider: generic
  url: https://foexle.github.io/helm-hmc/charts/aws-hosted-cp-extended
